server:
  port: 40008

spring:
  application:
    name: activemq-springboot-api

  redis:
    port: 6379
    host: 192.168.1.114
    timeout: 2000
    jedis:
      pool:
        max-active: 10
        max-idle: 8
        min-idle: 2
        enabled: true
  jmx:
    enabled: false

  activemq:
    broker-url: tcp://192.168.1.114:61616
    user: admin
    password: user*2022
    pool:
      enabled: true
      max-connections: 10
    in-memory: false
    packages:
      trust-all: true